### ISSUE TITLE
Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by FrancYescO** [AlexanderMac/http-z#39]
using it in vuejs any HttpZError exception will throw in `Error.captureStackTrace is not a function`

**Comment by AlexanderMac** [comment]
http-z is server-side package for now and it doesn't work on the client (or works with bugs). How do you build it for client? Using webpack?

**Comment by FrancYescO** [comment]
Yes

**Comment by AlexanderMac** [comment]
Then the problem is in Webpack, how it bundles node.js modules.
Wait until the official client bundle will be created: #31
