### ISSUE TITLE
Incorrect type defs in typescript

### ISSUE THREAD

**Issue by philiparvidsson** [AlexanderMac/http-z#63]
for query params and headers, you have typed the value as value?: string, meaning it can be string or undefined. looking through the code, these will never be undefined and so should be typed properly to value: string

https://github.com/AlexanderMac/http-z/blob/e7464193a225aaf7814d3355e19c77949c6188bc/src/utils.js#L45
https://github.com/AlexanderMac/http-z/blob/e7464193a225aaf7814d3355e19c77949c6188bc/src/parsers/base.js#L38-L39

thank you for an awesome lib

**Comment by AlexanderMac** [comment]
Thank you for raising the issue.
Fixed.
